server:
  port: 8901
  ##########seting logging level    ##########
logging:
    level:
      com.netflix: DEBUG
      org.springframework.web: DEBUG
      com.zjb: DEBUG

spring:
  application:
    name: ssoservice
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

##########将服务注册到eureka    start    ##########
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
##########将服务注册到eureka    end    ##########
signning:
  key: 223342s