spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/test?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    show-sql: true

server:
  port: 8083
