####
#Classpath and file-based solution
####
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
#          search-locations: file://<chapter3>/confsvr/src/main/resources/config/licensingservice,
#                              file://<chapter3>confsvr/src/main/resources/config/organizationservice
          searchLocations: classpath:config/,classpath:config/licensingservice
  profiles:
    active: native

#
#   This is the core configuration for a configuration service.  I have two examples here:
#
#       -  A configuration service which completelty loads the configuration for the services
#          from the local file server of the config service.  This should only be used for
#          demonstration purposes or for a small application with a limited number of services.
#
#       -  A configuraton service that uses a git-based repository to read the files from
#


###################################
#server:
#  port: 8888
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/FillixZhangJB/spmia-chapter3
#          searchPaths: /serviceconfigfiles/licensingservice
#          username: fillixzhang@163.com
#          password: ting52121
