server:
  port: 8761

#setting the logging level
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.zjb: DEBUG
    
eureka:
  client:
    fetch-registry: false  # 不在Eureka服务注册
    register-with-eureka: false # 不在本地缓存注册信息
  server:
    wait-time-in-ms-when-sync-empty: 5 # 服务器接收请求之前的等待时间 默认为5分钟